spring:
  datasource:
    url: jdbc:mysql://8.130.106.215:3306/forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: remote
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true

mybatis:
  mapper-locations: classpath:com/wjm/springmvc/mapper/*.xml
  type-aliases-package: com.wjm.springmvc.bean
#  config-location: classpath:mybatis-config.xml

server:
  port: 44444
  servlet:
    context-path: /demo2


file-save-path: /root/forum/img/